version: 1.0.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: 1.0.0.0
  file_version: '{version}'
  informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
build:
  parallel: true
  verbosity: minimal
before_build:
- pwsh: nuget restore -Verbosity quiet
- pwsh: dotnet tool install --global Codecov.Tool --version 1.7.1
test_script:
- pwsh: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.xml
- pwsh: codecov --file *\coverage.xml --flag $Env:configuration
artifacts:
- path: '**\*.nupkg'
  name: NuGet package
- path: '**\*.snupkg'
  name: NuGet symbols package
- path: ItsyBitsy.Bencoding.Docs\bin\Docs\
  name: docs
